/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CuisineAffinity { 'score' : number, 'cuisine' : string }
export interface Dish {
  'id' : string,
  'sweetness' : number,
  'richness' : number,
  'name' : string,
  'restaurantId' : string,
  'spice' : number,
  'cuisine' : string,
  'price' : number,
  'dietType' : string,
  'popularity' : number,
}
export interface TasteVector {
  'sweetness' : number,
  'richness' : number,
  'cuisineAffinities' : Array<CuisineAffinity>,
  'spice' : number,
  'vegetarian' : number,
}
export type Time = bigint;
export interface UserProfile {
  'tasteVector' : TasteVector,
  'name' : string,
  'createdAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, number, number, number],
    undefined
  >,
  'getAllDishes' : ActorMethod<[], Array<Dish>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'topCuisine' : string,
      'learningProgress' : number,
      'totalInteractions' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRecommendations' : ActorMethod<[string, string], Array<Dish>>,
  'getTasteVector' : ActorMethod<[], TasteVector>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordFeedback' : ActorMethod<[string, string, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];