/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Dish = IDL.Record({
  'id' : IDL.Text,
  'sweetness' : IDL.Float64,
  'richness' : IDL.Float64,
  'name' : IDL.Text,
  'restaurantId' : IDL.Text,
  'spice' : IDL.Float64,
  'cuisine' : IDL.Text,
  'price' : IDL.Float64,
  'dietType' : IDL.Text,
  'popularity' : IDL.Float64,
});
export const CuisineAffinity = IDL.Record({
  'score' : IDL.Float64,
  'cuisine' : IDL.Text,
});
export const TasteVector = IDL.Record({
  'sweetness' : IDL.Float64,
  'richness' : IDL.Float64,
  'cuisineAffinities' : IDL.Vec(CuisineAffinity),
  'spice' : IDL.Float64,
  'vegetarian' : IDL.Float64,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'tasteVector' : TasteVector,
  'name' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'getAllDishes' : IDL.Func([], [IDL.Vec(Dish)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'topCuisine' : IDL.Text,
          'learningProgress' : IDL.Float64,
          'totalInteractions' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecommendations' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Dish)],
      ['query'],
    ),
  'getTasteVector' : IDL.Func([], [TasteVector], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Dish = IDL.Record({
    'id' : IDL.Text,
    'sweetness' : IDL.Float64,
    'richness' : IDL.Float64,
    'name' : IDL.Text,
    'restaurantId' : IDL.Text,
    'spice' : IDL.Float64,
    'cuisine' : IDL.Text,
    'price' : IDL.Float64,
    'dietType' : IDL.Text,
    'popularity' : IDL.Float64,
  });
  const CuisineAffinity = IDL.Record({
    'score' : IDL.Float64,
    'cuisine' : IDL.Text,
  });
  const TasteVector = IDL.Record({
    'sweetness' : IDL.Float64,
    'richness' : IDL.Float64,
    'cuisineAffinities' : IDL.Vec(CuisineAffinity),
    'spice' : IDL.Float64,
    'vegetarian' : IDL.Float64,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'tasteVector' : TasteVector,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'getAllDishes' : IDL.Func([], [IDL.Vec(Dish)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'topCuisine' : IDL.Text,
            'learningProgress' : IDL.Float64,
            'totalInteractions' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecommendations' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Dish)],
        ['query'],
      ),
    'getTasteVector' : IDL.Func([], [TasteVector], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };